---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "gomod"
    directory: "/test/terratest"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
