---
name: Terratest

on:
  - pull_request

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version-file: test/terratest/go.mod
          cache: true
          cache-dependency-path: test/terratest/go.sum

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~1.1

      - name: Download Go Modules
        working-directory: test/terratest
        run: go mod download

      - name: Run Go Tests (terratest)
        working-directory: .
        run: 'ls -la ; cd test/terratest && ls -la; ls -la ../../examples/fixtures/terraform.tfvars; go test -v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
